services:
  - type: web
    name: geschenk25-api
    env: node
    buildCommand: npm install --production=false && npm run build
    startCommand: npm start
    postDeployCommand: npm run migrate
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: geschenk25-db
          property: internalDatabaseUrl
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: geschenk25-db
    databaseName: geschenk25
    user: geschenk25_user

